//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public string BILL_CODE { get; set; }
        public System.DateTime DATE_OF_ISSUE { get; set; }
        public int BILL_NUMBER { get; set; }
        public decimal SUBTOTAL { get; set; }
        public decimal DISCOUNT { get; set; }
        public Nullable<decimal> ISV { get; set; }
        public decimal TOTAL { get; set; }
        public string CHECK_OUT_CODE { get; set; }
        public string USER_CODE { get; set; }
    
        public virtual CHECK_OUT CHECK_OUT { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
