//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_OUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHECK_OUT()
        {
            this.BILL = new HashSet<BILL>();
        }
    
        public string CHECK_OUT_CODE { get; set; }
        public System.DateTime CHECK_OUT_TIME { get; set; }
        public int TOTAL_TIME { get; set; }
        public decimal FULL_CHARGE { get; set; }
        public string CHECK_OUT_STATE { get; set; }
        public string CHECK_IN_CODE { get; set; }
        public string USER_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILL { get; set; }
        public virtual CHECK_IN CHECK_IN { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
