//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_IN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHECK_IN()
        {
            this.CHECK_OUT = new HashSet<CHECK_OUT>();
        }
    
        public string CHECK_IN_CODE { get; set; }
        public string CLIENT_CODE { get; set; }
        public string VEHICLE_PLATE { get; set; }
        public System.DateTime CHECK_IN_TIME { get; set; }
        public string OBSERVATIONS { get; set; }
        public bool IS_DEL { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public string CHECK_IN_STATE { get; set; }
        public string PARKING_SPACE_CODE { get; set; }
        public string USER_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_OUT> CHECK_OUT { get; set; }
        public virtual PARKING_SPACE PARKING_SPACE { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual CLIENTS CLIENTS { get; set; }
    }
}
