//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        public string CLIENT_CODE { get; set; }
        public string CLIENT_DNI { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_LASTNAME { get; set; }
        public string CLIENT_ADDRESS { get; set; }
        public string CLIENT_PHONE { get; set; }
        public string CLIENT_EMAIL { get; set; }
        public Nullable<System.DateTime> INSERTED_AT { get; set; }
    }
}
