//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTS()
        {
            this.CHECK_IN = new HashSet<CHECK_IN>();
        }
    
        public string CLIENT_CODE { get; set; }
        public string CLIENT_DNI { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_LASTNAME { get; set; }
        public string CLIENT_ADDRESS { get; set; }
        public string CLIENT_PHONE { get; set; }
        public string CLIENT_EMAIL { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public string USER_ID { get; set; }
        public bool IS_DEL { get; set; }
    
        public virtual USERS USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_IN> CHECK_IN { get; set; }
    }
}
