//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_DATA
    {
        public string COMPANY_RTN { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_ADDRESS { get; set; }
        public string COMPANY_EMAIL { get; set; }
        public string COMPANY_PHONE { get; set; }
        public string LEGAL_FORM { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public bool DEL { get; set; }
        public string USER_ID { get; set; }
    
        public virtual USERS USERS { get; set; }
    }
}
