//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORRELATIVES
    {
        public string CORRELATIVE_CODE { get; set; }
        public string CORRELATIVE_DESCRIPTION { get; set; }
        public Nullable<int> CORRELATIVE_COUNTER { get; set; }
        public Nullable<System.DateTime> INSERTED_AT { get; set; }
        public Nullable<bool> IS_DEL { get; set; }
    }
}
