//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISCOUNTS()
        {
            this.DISCOUNTS_BILL = new HashSet<DISCOUNTS_BILL>();
        }
    
        public int DISCOUNT_ID { get; set; }
        public string DISCOUNT_VALUE { get; set; }
        public bool DISCOUNT_STATE { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public bool DEL { get; set; }
        public string USER_CODE { get; set; }
        public int DISCOUNT_TYPE_ID { get; set; }
        public int HOURS { get; set; }
        public int FREQUENCY_DAYS { get; set; }
    
        public virtual DISCOUNT_TYPE DISCOUNT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCOUNTS_BILL> DISCOUNTS_BILL { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
