//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNTS_BILL
    {
        public int DISCOUNTS_BILL_ID { get; set; }
        public int DISCOUNT_ID { get; set; }
        public string BILL_CODE { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public bool BIT { get; set; }
    
        public virtual DISCOUNTS DISCOUNTS { get; set; }
    }
}
