//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKING_TYPES
    {
        public string PARKING_TYPE_CODE { get; set; }
        public string DESCRIPTION_PARKING_TYPE { get; set; }
        public decimal PARKING_TYPE_PRICE { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public bool IS_DEL { get; set; }
    }
}
