//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKING_SPACE
    {
        public string PARKING_SPACE_CODE { get; set; }
        public int PARKING_SPACE_NUMBER { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public bool STATE { get; set; }
        public string USER_CODE { get; set; }
        public bool DEL { get; set; }
        public string PARKING_TYPE_CODE { get; set; }
    
        public virtual PARKING_TYPES PARKING_TYPES { get; set; }
    }
}
