//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKING_SPACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARKING_SPACE()
        {
            this.CHECK_IN = new HashSet<CHECK_IN>();
        }
    
        public string PARKING_SPACE_CODE { get; set; }
        public int PARKING_SPACE_NUMBER { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public bool STATE { get; set; }
        public string USER_CODE { get; set; }
        public bool DEL { get; set; }
        public string PARKING_FEE_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_IN> CHECK_IN { get; set; }
        public virtual PARKING_FEE PARKING_FEE { get; set; }
    }
}
