//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_PERMISSIONS
    {
        public int ROLE_PERMISSION_ID { get; set; }
        public int ROLE_ID { get; set; }
        public int PERMISSION_ID { get; set; }
        public Nullable<System.DateTime> INSERTED_AT { get; set; }
        public string USER_CODE { get; set; }
    
        public virtual USER_PERMISSIONS USER_PERMISSIONS { get; set; }
        public virtual USER_ROLES USER_ROLES { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
