//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARIES
    {
        public string SALARY_CODE { get; set; }
        public int BASE_SALARY { get; set; }
        public int AUMENTO { get; set; }
        public int TOTAL_SALARY { get; set; }
        public Nullable<System.DateTime> INSERTED_AT { get; set; }
        public string EMPLOYEE_CODE { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
    }
}
