//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.BILL = new HashSet<BILL>();
            this.CHECK_IN = new HashSet<CHECK_IN>();
            this.CHECK_OUT = new HashSet<CHECK_OUT>();
            this.CLIENTS = new HashSet<CLIENTS>();
            this.DISCOUNT_TYPE = new HashSet<DISCOUNT_TYPE>();
            this.DISCOUNTS = new HashSet<DISCOUNTS>();
            this.EMPLOYEE_USER = new HashSet<EMPLOYEE_USER>();
            this.PARKING_FEE = new HashSet<PARKING_FEE>();
            this.BILL_RANGE = new HashSet<BILL_RANGE>();
        }
    
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public System.DateTime INSERTED_AT { get; set; }
        public int ROLE_ID { get; set; }
        public bool IS_DEL { get; set; }
        public bool USER_STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_IN> CHECK_IN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_OUT> CHECK_OUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTS> CLIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCOUNT_TYPE> DISCOUNT_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCOUNTS> DISCOUNTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_USER> EMPLOYEE_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARKING_FEE> PARKING_FEE { get; set; }
        public virtual USER_ROLES USER_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_RANGE> BILL_RANGE { get; set; }
    }
}
